image: ubuntu:24.04

stages:
  - build

build-all-in-one:
  stage: build
  script:
    # Aggiorna e installa le dipendenze su una riga unica per evitare errori di spazi
    - apt-get update && apt-get install -y --no-install-recommends freeglut3-dev libglu1-mesa libgl1 libxi6 libxmu6 mingw-w64 make zip wget unzip
    
    # Esegue la build universale
    - make universal
    
  artifacts:
    paths:
      - hanoiTower_COMPLETE.zip
    expire_in: 1 week
    when: on_success
