image: gitlab-edu.supsi.ch:5050/dti-isin/labingsw/common:ubuntu2404-cg

stages:
  - build

build-all-in-one:
  stage: build
  script:
    # CORRETTO: Tutto su una riga senza backslash (\)
    - apt-get update && apt-get install -y --no-install-recommends freeglut3-dev libglu1-mesa libgl1 libxi6 libxmu6 mingw-w64 make zip wget unzip
    
    # Lancia la build universale (Linux + Windows)
    - make universal
    
  artifacts:
    paths:
      - hanoiTower_COMPLETE.zip
    expire_in: 1 week
    when: on_success
